eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1000/eureka/,http://peer2:1001/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip注册到注册中心
    instance-id:  user-server:2001 #注册到注册中心服务的id
server:
  port: 2001
spring:
  application:
    name: user-server  #服务的名字很重要


