server:
  port: 1001
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false  #不允许自己给自己注册
    fetchRegistry: false  #不允许获取微服务的通信地址列表
    serviceUrl: #微服务的注册地址
      defaultZone: http://peer1:1000/eureka/